### ISSUE TITLE
Add Dynamic Import when avalible.

### ISSUE THREAD

**Issue by masters3d** [exercism/typescript#121]
Dynamic import would allow us to be able to import the `exercise.example`but it that doesn't exist then we could just import `exercise`. This would help in development. 
https://github.com/tc39/proposal-dynamic-import

This would be similar to what we already do in the Objective-C track

```c

#if __has_include("AllergiesExample.h")
# import "AllergiesExample.h"
# else
# import "Allergies.h"
#endif


```

**Comment by masters3d** [comment]
Available now: 2.4
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html

**Comment by thedevelopnik** [comment]
So this will require a refactor of all existing exercises?

**Comment by masters3d** [comment]
Yeah, this would be a fund little project. It would mean that people can develop contributions and still be able to run using the normal yarn/npm process.

**Comment by thedevelopnik** [comment]
Cool, I'm going on vacation on the 20th and will have some free time to actually do fun little projects, I can tackle this over the break.

**Comment by masters3d** [comment]
Nice. Go for it!

**Comment by thedevelopnik** [comment]
Starting on it now.

**Comment by thedevelopnik** [comment]
@masters3d digging into this and I'm having some issues implementing it.

Started at the top level import, changing:

```typescript
import Acronym from './acronym'
```

to

```typescript
const Acronym = import('./acronym.example') || import('./acronym')
```

but now in the test code TS shows the error `Property 'parse' does not exist on type 'Promise<typeof ".../exercism/typescript/exercises/acronym/acronym.example">'`

It's a Promise that has yet to resolve.

That's why in the example you linked to above in the 2.4 release notes they show it in an `async/await` situation.

So if we move away from the top level and put it inside the test, we run into an issue because `describe` and `it` aren't async, so we can't await the conditional import statement `||`.

We end up with this:

```typescript
describe('Acronym are produced from', () => {
  it('title cased phrases', () => {
    return async function getModule() {
      const Acronym = await import('./acronym.example') || await import('./acronym')
      expect(Acronym.parse('Portable Network Graphics')).toEqual('PNG')
    }
  })
}
```

but now TS shows this error: `Property 'parse' does not exist on type 'typeof "/Users/davesudia/exercism/typescript/exercises/acronym/acronym.example"'.`

It's now a resolved promise but now I'm getting the TS error `Property 'parse' does not exist on type 'typeof "/Users/davesudia/exercism/typescript/exercises/acronym/acronym.example"'.`

Wat? If I comment out the `const Acronym` bit and add the regular `import Acronym from './acronym.example'` it's fine. So it seems to be reading the output from `import` differently than from `await import()`

Putting this here to see if there's something obvious I'm missing... I'll push up a branch so you can see the code as well.

**Comment by thedevelopnik** [comment]
https://github.com/exercism/typescript/pull/129

**Comment by thedevelopnik** [comment]
TypeScript will not compile if one of the imports isn't available/doesn't exist. This feature (in TS at least) seems to be more for memory/bundle optimization than for contingent importing. Closing this issue.

**Comment by masters3d** [comment]
thanks for trying @thedevelopnik ! lets leave it open. i’d like to give it a try.

**Comment by masters3d** [comment]
the next thing to try would be to yse the .then .catch
https://github.com/basarat/typescript-book/blob/master/docs/project/dynamic-import-expressions.md

**Comment by masters3d** [comment]
Cant have top level await. May need to drop down to node for this feature
https://github.com/tc39/ecmascript-asyncawait/issues/9#issuecomment-127427447
https://gist.github.com/Rich-Harris/0b6f317657f5167663b493c722647221

**Comment by masters3d** [comment]
This works but it is not ideal:

```typescript


const fileExists = require('file-exists');

describe('Hello World', async () => {
  async function loadModule(){
    let example = ''
    if (fileExists.sync('hello-world.example.ts')) {
      example = '.example'
    }
    return await import('./hello-world' + example)
    .then(module => module.default)
  }

  it('says hello world with no name', async () => {
    expect(HelloWorld.hello()).toEqual('Hello, World!')
  })

  it('says hello to bob', async () => {
    expect(HelloWorld.hello('Bob')).toEqual('Hello, Bob!')
  })

  it('says hello to sally', async () => {
    expect(HelloWorld.hello('Sally')).toEqual('Hello, Sally!')
  })

  const HelloWorld = await loadModule()

```

**Comment by masters3d** [comment]
The next step would be to warp this into a library or function so that we could say. 
```JS
const HelloWorld  = importElse('./hello-world.example', './hello-world')
```

**Comment by masters3d** [comment]
On the flip-side, We could export conditionally on the user facing stub file (not example). 

https://stackoverflow.com/a/43591970/3705470
```JS
const exportedAPI = shouldUseMock ? mockAPI : realAPI
export default exportedAPI
```

**Comment by masters3d** [comment]
2.9 seems to be the version that we want fo this:
https://github.com/Microsoft/TypeScript/issues/14844

**Comment by SleeplessByte** [comment]
We have top-level track package.json tooling now that works without dynamic import.
