### ISSUE TITLE
[Grade School] Can't use Readonly<> types for later tests

### ISSUE THREAD

**Issue by sfre-coop** [exercism/typescript#1259]
I think the _right_ way to turn off modification would be to use `Readonly<>` generics, which would enforce the requirement during compilation. Unfortunatly, using them also means that the tests don't compile. Not sure how to get out of this.

And thanks for all the work.

**Comment by SleeplessByte** [comment]
@sfre-coop could you post your solution so I can look into what exactly is failing?

**Comment by sfre-coop** [comment]
```
type Student = string
type Grade = number;
type Students = ReadonlyArray<Student>

// Ideally this would user Readonly<> generics but that stops the tests from compiling.
type Roster = Record<Grade, Students>

export class GradeSchool {
  private _roster:  Roster = {}
  roster() : Roster {
    return this._roster
  }

  add(student: Student, grade: Grade) : void {
    this.remove(student);
    this._roster[grade] = [...this.grade(grade), student].sort()
  }

  private remove(student: string) : void {
    for (let g in this._roster) {
      let students = this._roster[g]
      if (students.includes(student)) {
        this._roster[g] = students.filter(s => s !== student)
        break
      }
    }
  }

  grade(grade: Grade): Students {
    return this._roster[grade] || []
  }
}
```

**Comment by sfre-coop** [comment]
If you try this solution, then the calls to push at lines 68 and 75 in the tests don't compile.

**Comment by SleeplessByte** [comment]
That's correct, because you cannot push to a readonly array!

`readonly T[]` and `ReadonlyArray<T>` are often used to signal one of two things:

- this function _will not mutate_ that parameter
- callers of this function _may not mutate_ the result

Neither is true for this exercise as the goal is to return a result that may be mutated, _because_ it was safely disconnected from the source data (by duplicating it). Therefore, readonly isn't a good fit for this exercise.

Let me know if this explanation makes sense or you'd like further elaboration or examples.

**Comment by sfre-coop** [comment]
OK. I didn't see that in the text. My implementation disabled the call to push(), which passes the test.

**Comment by SleeplessByte** [comment]
Yes, the text doesn't explicitly say what I said in my post, because the tests say nothing about the internal immutability or lack thereof. We only test two things:

1. `'roster cannot be modified outside of module'` meaning you cannot mutate the roster inside the school without using `add`.
2. `'roster cannot be modified outside of module using grade()'` meaning you cannot mutate a grade inside the roster, inside the school without using `add`

Neither says that the result must be read-only, only that nothing (including the result) may cause the internals to change.

----

Regardless of what the text says @sfre-coop, in your posted solution you denote:

```typescript
// Ideally this would user Readonly<> generics but that stops the tests from compiling.
type Roster = Record<Grade, Students>
```

But that would mean that you cannot type your internal roster as `Roster` because then `add` and `remove` would never work. This would fail compilation inside the solution (ignoring the tests). Does that make sense?
