### ISSUE TITLE
Typescript tests broken

### ISSUE THREAD

**Issue by technovangelist** [exercism/typescript#316]
None of the tests seem to be working. For instance on the Hello World exercise, I submitted successfully, but the tests never worked. First the tests mentioned in the article don't agree with whats installed. And then all the errors that your exercise points out arent there. When you run yarn test, you get: 
`../../../../../node_modules/@types/mocha/index.d.ts:2680:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'beforeEach' must be of type 'Lifecycle', but here has type 'HookFunction'`

**Comment by SleeplessByte** [comment]
Hi there.

It's actually not the Exercism typescript tests that are broken, but your local environment. The problem here is that in the parent tree of the exercism folder (exactly at `../../../../../`), there is a "project (`package.json` or `node_modules`). `tsc` is picking up type definitions here which conflict with what we use (`jest` and `jasmine`).

The easiest solution is to purge the `node_modules` folder at the location.

However, we _can_ (and will) change the configuration in `tsconfig.json` to try to alleviate this as well by making `tsc` stop looking upwards, something that's possible now but wasn't really a long while back.

Feel free to respond here if you need more support.
