### ISSUE TITLE
Is there a test missing in the grade-school exercise?

### ISSUE THREAD

**Issue by pedrorolo** [exercism/typescript#361]
When implementing this exercise I assumed a student could only belong in a single grade. This requirement makes the exercise interesting because the most convenient storage data structure is not the one that is meant to serve as output, and I wonder to which degree this wasn't the intended challenge underlying this exercise. 

I thus propose adding the following test to the exercise: 

```
  it("A student can't be in two different grades", () => {
    gradeSchool.addStudent('Aimee', 2)
    gradeSchool.addStudent('Aimee', 1)

    const emptyGrade = gradeSchool.studentsInGrade(2)
    const expectedDb = new Map(Object.entries({ 2: ['Aimee'] }))
    expect(emptyGrade).toEqual([])
  })
```

I would like to make a pull-request with this change, but first I wanted to confirm if this implicit requirement makes sense.

**Comment by SleeplessByte** [comment]
This exercise was meant to teach/test the students understanding of immutability. The internal structure for storage, and the method of ensuring the return values are copies of the data are open for the student.

What structure was possible _before_ this test and isn't after? I personally don't see the value in complicating the exercise, also because `Aimee` could be a different person in both grades (ie. names aren't necessarily unique).

**Comment by pedrorolo** [comment]
> What structure was possible _before_ this test and isn't after? I personally don't see the value in complicating the exercise, also because `Aimee` could be a different person in both grades (ie. names aren't necessarily unique).

I am sorry, but names are necessarily unique, due to how the problem is specified on the [README](https://github.com/exercism/typescript/blob/master/exercises/grade-school/README.md):

> Note that all our students only have one name. (It's a small town, what do you want?)

And now, by noticing this requirement in the README, it becomes more and more clear that it makes sense to add the mentioned test case to this exercise. Or otherwise make the README more clear, by stating whether a student can simultaneously belong in different grades or not.

IMHO the exercise is a much more interesting challenge when a student cannot belong to two different grades, because one is forced to [output a different data-structure than the one which is a better fit for storage and manipulation
](https://github.com/pedrorolo/exercism/blob/master/typescript/grade-school/grade-school.ts).

**Comment by SleeplessByte** [comment]
No need to apologise. You're right. In this exercise names are unique.

That said, forcing a certain implementation is not the goal of _any_ V2 exercise in Exercism. Your proposed test case **does not** force said implementation (it can still be satisfied without using a Map), so I actually don't mind having it.

You may open a PR that adds the test case and changes the example so that it matches the implementation. It would also be great if you could add the test case to the problem-specifications repository, so that _other tracks_ may benefit from this ❤️

**Comment by SleeplessByte** [comment]
This has been merged!
