### ISSUE TITLE
Typescript: Using yarn lint will fail with error ' was unexpected at this time

### ISSUE THREAD

**Issue by marekpetak** [exercism/typescript#45]
moved from https://github.com/exercism/exercism.io/issues/3572

Typescript excecism using Windows OS (8.1)

When running `yarn lint` above error will occur.
error details:

    yarn lint v0.24.5                           
    $ tslint '*.ts?(x)'; exit 0                 
    ' was unexpected at this time.              
                                            
    E:\exercism\typescript\hamming>  "E:\exercism\typescript\hamming\node_modules\.bin\\node.exe"  "E:\exercism\typescript\hamming\node_modules\.bin\\..\tslint\bin\tslint" '*.ts?(x)'; exit 0
    error Command failed with exit code 255.    

changing package.json from

    "scripts": {
        "test": "jest --no-cache",
        "lint": "tslint '*.ts?(x)'; exit 0"
    }

to

    "scripts": {
        "test": "jest --no-cache",
        "lint": "tslint *.ts?(x)"
    }

not sure what is the reason behind `exit 0`

**Comment by NobbZ** [comment]
Basically there seem to be 2 problems in a single post, let me inspect them one after the other:

---

As I already have mentioned in the original issue, removing the quotes will cause issues on linux machines.

With quotes, the argument `*.ts?(x)` is passed as is to the program (`yarn`) in this case, and has to be parsed by it. Without the quotes, most shells will try to expand the glob. The shell expanded filelist were probably empty, since bash would only let files in which match the following regex: `~/.*\.ts.\(x\)/`, and there are simply no such files in the directory.

On windows, those quotes are for some reason I am not aware off, a syntactic error as it seems, but windows does not do any glob-expansion but passes the argument to the program literally anyway (well, there are exceptions, but those don't matter in this case).

So in general we need to find a way to make the `yarn` invocation work on windows as on windows.

---

The `exit 0` is to signal that there was no error.

I'm not sure if at all there is something similar in windows, but I don't like it anyway. I have a prompt which is tainted in dark red when I had a non-zero exit code, and I really dislike to have to read the output instead of simply getting signaled by my prompt if there was something or not.

Until now I did not realize that there was the `exit 0` after invocating `tslint`, but until now I simply thought `tslint` weren't doing exit codes properly and just lived with it. Sadly I haven't a machine at hand where I could test now if there are actually non-zero exit codes on found lints.

Therefore I'd suggest to simply remove the `exit 0` once and for all.

**Comment by marekpetak** [comment]
So the intention was to simply force tslint to exit with 0, even if the output was different from 0?

**Comment by NobbZ** [comment]
Yeah that was possibly the intention behind exit, but simply removing exit does not solve your problem that windows doesn't like the quotes.

**Comment by masters3d** [comment]
yeah. The exit 0 was meant for CI. On the new version pushed a couple of days ago we have a special `lintci`. 

In other news, I guess single quotes are not supported in [windows](https://github.com/palantir/tslint/issues/1375#issuecomment-230993311). @marekpetak  can you try with double quotes ? If that works we can update our repo. We currently do not have any windows boxes on CI.

**Comment by NobbZ** [comment]
Just to make sure, trying using doublequotes means using the following snippet?

```json
"scripts": {
    "test": "jest --no-cache",
    "lint": "tslint \"*.ts?(x)\""
}
```

**Comment by masters3d** [comment]
that is what I am thinking but I do not have a way to test on windows yet. Here is more info: https://github.com/eslint/eslint/issues/5796#issuecomment-206717297

**Comment by masters3d** [comment]
This buy fix is failing on windows. Anybody with windows? https://github.com/exercism/typescript/pull/48

**Comment by marekpetak** [comment]
"lint": "tslint \"*.ts?(x)\"; exit 0"

will fail on windows. removing `;exit 0` works
