### ISSUE TITLE
implement linked-list

### ISSUE THREAD

**Issue by lilislilit** [exercism/typescript#71]
As per #37, port exercise from ecmascript track

**Comment by jspengeman** [comment]
Hey guys, I can pick this one up. I should have something ready for review in a couple of days.

**Comment by jspengeman** [comment]
Just finished with the example file. It looks kind of mediocere when I use the type `any` for the value of the node and return values of `pop` and `unshift`. Any thoughts on making it generic? Considering a class `Node<T>` with a `LinkedList<T>` class as well. Although, it may be out of scope for the exercise. Thoughts?

**Comment by masters3d** [comment]
Look at other types languages with generics? 

https://github.com/exercism/swift/blob/master/exercises/linked-list/Sources/LinkedListExample.swift

**Comment by jspengeman** [comment]
Thanks, although the question was not how to implement it but rather if it was in scope for the person completing the exercise to be expected to have to complete it using generics. The example you posted actually answered _that_ question.

**Comment by masters3d** [comment]
Oh I see. Usually we try to use all the facilities the language offers so we can show case their features. What is hard sometimes is how to write the tests in a way that will take advantages of the features of the language.

**Comment by jspengeman** [comment]
Good to now. Thank you!

**Comment by jspengeman** [comment]
I am a couple of questions:

1) How do I know what to put for the UUID of the exercise in the `config.json`, I am looking at the [ecmascript](https://github.com/exercism/ecmascript/blob/master/config.json#L147) repo as example? 

2) In the ecmascript repository there are tests for the `delete` method [here](https://github.com/exercism/ecmascript/blob/master/exercises/linked-list/linked-list.spec.js#L69) but the delete method needing to be implemented is not mentioned in the readme similar to how `push`, `pop`, `shift`, and `unshift`, is that intentional?

**Comment by masters3d** [comment]
1. The UUID is a new thing that was introduced. It needs to be unique across all the tracks so that part should not be there same. You can get this from a UUID generator website. This is still new to me but there are some more hints on this on the general docs about contributing. If you still need help with this, you can ask somebody here https://gitter.im/exercism/support

2. Each track is able to change their own version of the readme to match what they want to do with their track. This is also new. It used to be that there was only one master version that everybody had to follow.

**Comment by jspengeman** [comment]
Great, thank you for all the help thus far. I will have a PR out today.

**Comment by masters3d** [comment]
The docs are changing but here is an older commit: 
https://github.com/exercism/docs/blob/39109e34d3590b4b9399600a57798601353e96d2/language-tracks/configuration/README.md

You can also use this linter to generate a unique UUID
https://github.com/exercism/docs/blob/master/language-tracks/configuration/configlet.md
https://github.com/exercism/configlet/releases
