### ISSUE TITLE
Automate migration of exercises from ECMAScript track

### ISSUE THREAD

**Issue by BrianDGLS** [exercism/typescript#79]
I just added an exercise to this repo from the ECMAScript track. It looks to me like this would be quite an easy process to automate.

**Comment by masters3d** [comment]
Since TS is a superset then in theory all ES problems are valid TS problems.  

Usually we try to use all the facilities the language offers so we can show case their features. 

In most cases the test files can be used with little modifications. 

What is hard sometimes is how to write the tests in a way that will take advantages of the features of the language.

**Comment by dsudia** [comment]
Yeah, there are also places where the ES solutions take advantage of JS's soft types, like a place where something could be a string or undefined. The difficulty in automating that to TS is the exact problem that TS was meant to solve: it's hard for a machine to determine what those types are supposed to/could be.
